/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <AppKit/NSControl.h>

@interface NSScroller : NSControl (Private)

+ (void)_aquaScrollerBehaviorChanged:(id)fp8;
+ (void)_aquaScrollerVariantChanged:(id)fp8;
+ (float)scrollerWidth;
+ (float)scrollerWidthForControlSize:(unsigned int)fp8;
+ (void)initialize;
+ (int)_arrowsConfig;
+ (void)_setArrowsConfig:(int)fp8;
+ (void)_drawEndCapInRect:(NSRect)fp8;
- (BOOL)_hasSeparateArrows;
- (double)_repeatTime;
- (id)_setWindow:(id)fp8;
- (id)initWithFrame:(NSRect)fp8;
- (void)dealloc;
- (void)finalize;
- (BOOL)isOpaque;
- (BOOL)isFlipped;
- (void)drawParts;
- (NSRect)_drawingRectForPart:(unsigned int)fp8;
- (NSRect)rectForPart:(unsigned int)fp8;
- (void)checkSpaceForParts;
- (unsigned int)usableParts;
- (id)target;
- (void)setTarget:(id)fp8;
- (SEL)action;
- (void)setAction:(SEL)fp8;
- (void)_adjustForGrowBox;
- (void)setFrameOrigin:(struct _NSPoint)fp8;
- (void)setFrameSize:(NSSize)fp8;
- (void)setArrowsPosition:(unsigned int)fp8;
- (unsigned int)arrowsPosition;
- (void)setControlTint:(unsigned int)fp8;
- (unsigned int)controlTint;
- (void)setControlSize:(unsigned int)fp8;
- (unsigned int)controlSize;
- (unsigned int)_realControlTint;
- (void)setEnabled:(BOOL)fp8;
- (struct __CFDictionary *)_copyCompositeCoreUIDrawOptions;
- (void)_old_drawArrow:(unsigned int)fp8 highlightPart:(unsigned int)fp12;
- (void)drawArrow:(unsigned int)fp8 highlightPart:(unsigned int)fp12;
- (void)drawArrow:(unsigned int)fp8 highlight:(BOOL)fp12;
- (void)_old_drawKnob;
- (void)drawKnob;
- (void)_old_drawKnobSlotInRect:(NSRect)fp8 highlight:(BOOL)fp24;
- (void)drawKnobSlotInRect:(NSRect)fp8 highlight:(BOOL)fp24;
- (void)drawRect:(NSRect)fp8;
- (void)highlight:(BOOL)fp8;
- (void)_getPartStruct:(struct _PartStruct *)fp8 numberOfParts:(unsigned int *)fp12 withInnerBounds:(NSRect)fp16;
- (unsigned int)_testPartUsingDestinationFloatValue:(struct _NSPoint)fp8;
- (unsigned int)testPart:(struct _NSPoint)fp8;
- (BOOL)sendAction:(SEL)fp8 to:(id)fp12;
- (void)trackKnob:(id)fp8;
- (void)trackScrollButtons:(id)fp8;
- (void)trackPagingArea:(id)fp8;
- (void)mouseDown:(id)fp8;
- (unsigned int)hitPart;
- (float)floatValue;
- (double)doubleValue;
- (float)knobProportion;
- (void)setKnobProportion:(float)fp8;
- (void)setFloatValue:(float)fp8 knobProportion:(float)fp12;
- (void)setFloatValue:(float)fp8;
- (void)setDoubleValue:(double)fp8;
- (BOOL)acceptsFirstMouse:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (void)setInterfaceStyle:(unsigned int)fp8;
- (void)_windowChangedKeyState;

@end

